name: API Tests

on:
 # schedule:
  #  - cron: "0 12 * * 1-5"
  workflow_call:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  Tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        cd api-testing
        pip install -r requirements.txt
    - name: Test with pytest
      run: |
        cd api-testing
        pytest --env local --alluredir=./allure-results tests/
